create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  company text not null default '未识别公司名',
  role text not null default '未识别岗位名',
  jd text not null default '',
  resume text not null default '',
  email_language text not null default '未记录',
  ai_mode text not null default 'fallback',
  status text not null default '待申请',
  application_link text,
  tailored_bullets jsonb not null default '[]'::jsonb,
  email_subject text not null default '',
  email_body text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.applications enable row level security;

drop policy if exists "applications_public_select" on public.applications;
create policy "applications_public_select"
on public.applications
for select
using (true);

drop policy if exists "applications_public_insert" on public.applications;
create policy "applications_public_insert"
on public.applications
for insert
with check (true);

drop policy if exists "applications_public_update" on public.applications;
create policy "applications_public_update"
on public.applications
for update
using (true)
with check (true);

drop TABLE if exists public.application_history cascade;